### PR TITLE
Using PHP 5.3 namespaces with composer psr-0 autoload

### PR DESCRIPTION
**Pull request by dizda**

### CODE REVIEW

**Comment by matthiasplappert** [comment]
Correct me if I'm wrong, but this will only work with PHP >= 5.3.0, right? So can you change the composer.json file to reflect that?

**Comment by dizda** [comment]
You right :-)

**Comment by dizda** [comment]
ping @matthiasplappert

**Comment by matthiasplappert** [comment]
Thanks for fixing this!

**Comment by dizda** [comment]
Thanks to you, to provide useful libs :-)

**Pull request merged**
